---
- name: Create EC2 Instance using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: eu-north-1
    instance_type: t3.micro
    ami_id: ami-0fa91bc90632c73c9   # Amazon Linux 2 (Mumbai)
    key_name: project-1
    security_group: launch-wizard-1
    instance_name: Ansible-EC2

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        count: 1
        tags:
          Environment: Dev
          CreatedBy: Ansible

